config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :property_owners
  root to: 'home#index'
  resources :properties, only: [:show, :new, :create]
  resources :property_types, only: [:show, :new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :property_type
  validates :title, :description, :rooms, :bathrooms, :daily_rate, presence: {message: "não pode ficar em branco"}
end

app/models/property_owner.rb
class PropertyOwner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/property_type.rb
class PropertyType < ApplicationRecord
  has_many :properties
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @properties = Property.all
    @property_types = PropertyType.all
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def show
    @property = Property.find(params[:id])
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.create(params.require(:property)
      .permit(
        :title,
        :description,
        :rooms,
        :bathrooms,
        :parking_slot,
        :pets,
        :daily_rate,
        :property_type_id
      ))

    if @property.save
      redirect_to @property
    else
      render :new
    end
  end
end

app/controllers/property_types_controller.rb
class PropertyTypesController < ApplicationController
  def show
    @property_type = PropertyType.find(params[:id])
  end

  def new
    @property_type = PropertyType.new
  end

  def create
    @property_type = PropertyType.create(params.require(:property_type).permit(:title))

    if @property_type.save
      redirect_to @property_type
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<header>
  <h3 class="p-2">Boas vindas ao sistema de locação de apartamentos</h3>
</header>

<aside>
  <h3>Filtrar por tipo:</h3>
  <nav>
    <% @property_types.each do |pt| %>
      <%= link_to pt.name, property_type_path(pt.id) %>
    <% end %>
  </nav>
</aside>

<% if @properties.empty? %>
  <div>Nenhum imóvel disponível</div>
<% end %>
<section class="flex flex-wrap">
<% @properties.each do |p| %>
<div class="max-w-sm mx-auto mt-16 text-center max-w-sm rounded overflow-hidden shadow-lg p-10 bg-white">

  <%= link_to p.title, property_path(p.id), class: "mb-4 text-2xl py-4 px-2 text-green-800 font-semibold hover:text-green-500 transition duration-300" %>
  <p class="text-base leading-snug text-justify overflow-ellipsis">
    <%= p.description %>
  </p>
  <p class="text-base leading-snug text-justify">
    Quartos: <%= p.rooms %>
  </p>

</div>
<% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-green-200">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/properties/new.html.erb
<h1>Cadastro de imóveis</h1>

<% if @property.errors.any? %>
  <% @property.errors.full_messages.each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<%= form_with(model: @property) do |f| %>
  <%= f.label :title, 'Título' %>
  <%= f.text_field :title %>

  <%= f.label :description, 'Descrição' %>
  <%= f.text_field :description %>

  <%= f.label :property_type_id, 'Tipo' %>
  <%= f.collection_select :property_type_id, PropertyType.all, :id, :name %>

  <%= f.label :rooms, 'Quartos' %>
  <%= f.text_field :rooms %>

  <%= f.label :bathrooms, 'Banheiros' %>
  <%= f.text_field :bathrooms %>

  <%= f.label :daily_rate, 'Diária' %>
  <%= f.text_field :daily_rate %>

  <%= f.check_box :pets %>
  <%= f.label :pets, 'Aceita Pets' %>

  <%= f.check_box :parking_slot %>
  <%= f.label :parking_slot, 'Vaga de Estacionamento' %>

  <%= f.submit 'Enviar' %>

<% end %>

app/views/properties/show.html.erb
<h1><%= @property.title %></h1>

<h2><%= @property.description %></h2>

Quartos: <%= @property.rooms %>
Banheiros: <%= @property.bathrooms %>
Aceita Pets:
<% if @property.pets? %>
  Sim
<% else %>
  Não
<% end %>

Estacionamento:
<% if @property.parking_slot? %>
  Sim
<% else %>
  Não
<% end %>

Diária:
<%= number_to_currency @property.daily_rate, unit: 'R$', separator: ',', format: "%u %n" %>

Tipo:
<%= @property.property_type.name %>

<%= link_to 'Voltar', root_path %>

app/views/property_owners/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/property_owners/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/property_types/show.html.erb
<h1>Imóveis do tipo <%= @property_type.name %></h1>

<%= @property_type.properties.each do |p| %>
  <%= p.title %>
<% end %>

app/views/shared/_navbar.html.erb
	<nav class="bg-white shadow-lg">
		<div class="max-w-6xl mx-auto px-4">
			<div >
				<div class="flex justify-between items-center space-x-7">
					<!-- Website Logo -->
          <div>
            <h1 class="text-green-500 font-bold text-4xl">Flats</h1>
					</div>
					<!-- Primary Navbar items -->
					<div class="hidden md:flex items-center space-x-1">
						<a
							href=""
							class="py-4 px-2 text-green-500 border-b-4 border-green-500 font-semibold "
							>Home</a
						>
						<a
							href=""
							class="py-4 px-2 text-gray-500 font-semibold hover:text-green-500 transition duration-300"
							>Services</a
						>
						<a
							href=""
							class="py-4 px-2 text-gray-500 font-semibold hover:text-green-500 transition duration-300"
							>About</a>
						<%= link_to 'Cadastrar Imóvel', new_property_path, class: "py-4 px-2 text-gray-500 font-semibold hover:text-green-500 transition duration-300" %>
						<% if property_owner_signed_in? %>
							<%= link_to 'Sair', new_property_owner_session_path, class: "py-4 px-2 text-gray-500 font-semibold hover:text-green-500 transition duration-300" %>
						<% else %>
							<%= link_to 'Entrar', new_property_owner_session_path, class: "py-4 px-2 text-gray-500 font-semibold hover:text-green-500 transition duration-300" %>
						<% end %>


							
					</div>
				</div>
			</div>
		</div>
	</nav>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>